apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
---
apiVersion: "falcon.services/v1"
kind: MongoService
metadata:
  namespace: test-ns
  name: mongodb
spec:
  name: test
  label: test
  url: https://some.url.com
  payload: |
    apiVersion: mongodb.com/v1
    kind: MongoDBUser
    metadata:
      name: my-replica-set-x509-user
    spec:
      db: $external
      mongodbResourceRef:
        name: my-replica-set
      roles:
        - db: admin
          name: dbOwner
      username: 'CN=my-replica-set-x509-user,OU=cloud,O=MongoDB,L=New York,ST=New York,C=US'